qemu-system-x86_64                                                             \
    -machine accel=hvf                                                         \
    -cpu     host                                                              \
    -smp     4                                                                 \
    -m       8G                                                                \
    -hda     debian.qcow2                                                      \
    -kernel  boot/linux                                                        \
    -initrd  boot/initrd.gz                                                    \
    -append  "console=ttyS0"                                                   \
    -no-reboot                                                                 \
    -nographic
